name: ampache

services:
  ampache:
    image: ampache/ampache:nosql-develop
    container_name: ampache
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./data/config:/var/www/config
      - ./data/log:/var/log/ampache
      - ./data/media:/media
    environment:
      DISABLE_INOTIFYWAIT_CLEAN: ${DISABLE_INOTIFYWAIT_CLEAN-0}
