name: ampache

services:
  ampache:
    image: ampache/ampache:nosql-develop
    container_name: ampache
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./data/config:/var/www/config
      - ./data/log:/var/log/ampache
      - ./data/media:/media
    environment:
      MYSQL_USER: ${MYSQL_USER-admin}
      MYSQL_PASS: ${MYSQL_PASS-**Random**}
      DB_NAME: ${DB_NAME-}
      DB_HOST: ${DB_HOST-}
      DB_USER: ${DB_USER-}
      DB_PASSWORD: ${DB_PASSWORD-}
      DB_PORT: ${DB_PORT-}
      DISABLE_INOTIFYWAIT_CLEAN: ${DISABLE_INOTIFYWAIT_CLEAN-0}
      FORCE_INSTALL: ${FORCE_INSTALL-0}
      AMPACHE_DB_USER: ${AMPACHE_DB_USER-}
      AMPACHE_DB_PASSWORD: ${AMPACHE_DB_PASSWORD-}
      AMPACHE_ADMIN_USER: ${AMPACHE_ADMIN_USER-}
      AMPACHE_ADMIN_PASSWORD: ${AMPACHE_ADMIN_PASSWORD-}
      AMPACHE_ADMIN_EMAIL: ${AMPACHE_ADMIN_EMAIL-}
